spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store?scema=public
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:

    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
